### ISSUE TITLE
Build failed: node-sass not installed

### ISSUE THREAD

**Issue by shonderdos** [ultimatecourses/ngrx-store-effects-app#21]
OS: MacOS 10.13.4
npm: 5.7.1
node: 9.8.0

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-59_binding.node": 

Looking at the url, 'darwin-x64-59' does not exists.

Fix: `npm install node-sass@4.6.0 --save-dev`
4.6.0 was het next release, thats the only reason I chose that version.

**Comment by dmnrmr** [comment]
Use `4.9.0`

**Comment by jordanwilcken** [comment]
I ran `npm install -g node-sass` and that gave me version 4.11.0 of node-sass. Then I updated the package.json to use that version. And then I restarted VSCode.

**Comment by zimejin** [comment]
Install Yarn, then run yarn add node-sass.
